### ISSUE TITLE
Issue on Puppet 5.1.0 ( Illegal character URIParser)

### ISSUE THREAD

**Issue by hlzhlm** [bodgit/puppet-openldap#52]
Hi,
I am currently facing issue when running on Puppet Agent that says illegal character in file:///puppet/v3/file_content/modules/openldap/RedHat/slapd.d/cn=config/olcDatabase=%7B0%7Dconfig.ldif

If you notice the illegal char is curly braces { }. Puppet has raised this ticket and fixed in 5.1.5 ( https://tickets.puppetlabs.com/browse/SERVER-1954 ). However, I can't upgrade my puppet version to 5.1.5. Can you help to solve this issue since you are supporting until Puppet 6.

**Comment by bodgit** [comment]
It looks like a fundamental bug in Puppet that I can't work around, those files need to be named specifically that way for them to work in OpenLDAP.

I support the language features, etc. in Puppet 4/5, but I generally won't work around silly release bugs, especially if it's already been fixed in a later release, sorry.
